version: '3'

services:
  nexus-network:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-node
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./nexus-data:/home/nexus/.nexus
    ports:
      - "8080:8080"
    environment:
      - DEBIAN_FRONTEND=noninteractive